Nguồn:
1. https://www.youtube.com/watch?v=faheDNsr-B4&list=PLZEIt444jqpCyaGWG1Jvq2ylfOdjppEOR

# Cài đặt OpenCV

1. Truy cập: https://opencv.org/releases/ tải về phiên bản OpenCV cho hệ điều hành tương ứng.
2. Giải nén OpenCv ra 1 thư mục nào đó.
3. Truy cập vào opencv --> build --> python --> cv2 --> chọn phiên bản python tương ứng với máy (Ví dụ máy tôi là python 3.7)--> copy file đó và cho vào `C:\Program Files\Python37\Lib\site-packages`.
4. Mở cmd và chạy lệnh `pip install opencv-python`
5. Test lại bằng cách mở python và `import cv2`

# Mở ảnh với OpenCV

In [9]:
import cv2
img = cv2.imread('./avatar.jpg')
cv2.imshow('image', img)
cv2.waitKey(0) # chờ ấn 1 phím gì đó rồi mới tắt
cv2.destroyAllWindows() # giải phóng

# Lưu một bức ảnh và vẽ một đường thẳng

In [6]:
img = cv2.imread("./avatar.jpg")
cv2.line(img, (0,0), (400, 300), (255,0,0), 5) 
# img, toạ độ bắt đầu, toạ độ kết thúc , (r,g,b),pixel width
cv2.imwrite('./ly.jpg', img)
cv2.destroyAllWindows()

# Thao tác với pixel ảnh

In [13]:
img = cv2.imread('./ly.jpg')
px = img[0][0]
print(px)

[252   0   0]


In [15]:
img[0][0] = [1, 1, 1]
for i in range(100):
    img[i][i] = [1, 1, 1]
    img[i + 1][i + 1] = [1, 1, 1]
px = img[0][0]
px

array([1, 1, 1], dtype=uint8)

In [16]:
cv2.imwrite('./ly2.jpg',img)

True

# Đọc thuộc tính và cắt ghép, đổi kênh màu ảnh

In [18]:
img = cv2.imread('./avatar.jpg')
img.shape # kích thước ảnh

(718, 720, 3)

In [19]:
# đọc ảnh xám
img = cv2.imread('./avatar.jpg', 0)
img.shape

(718, 720)

In [21]:
img.size # kích thước ảnh = byte

516960

In [22]:
img.dtype

dtype('uint8')

In [24]:
# cắt ảnh
subimg = img[200: 300, 200: 500]
cv2.imshow("image", subimg)
cv2.waitKey()

-1

In [27]:
# chuyển kênh màu
img = cv2.imread('./avatar.jpg')
subimg = img[:,:,2]
cv2.imshow("image", subimg)
cv2.waitKey()

-1

# Hoà trộn 2 bức ảnh với nhau

Điều kiện: cùng kênh màu (ảnh màu hoặc xám), cùng kích thước

In [35]:
img1 = cv2.imread('./avatar.jpg')
img2 = cv2.imread('./anh2.jpg')
img1 = img1[100:700, 100:700]
img2 = img2[100:700, 100:700]

img3 = cv2.add(img1, img2)
cv2.imshow("image", img3)
cv2.waitKey()

-1

# Tách một đối tượng có màu nhất định ra khỏi ảnh

In [37]:
import numpy as np
img = np.uint8([[[232, 162, 0]]])
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
hsv_img

array([[[ 99, 255, 232]]], dtype=uint8)

In [45]:
img = cv2.imread('./anh3.png')
# chuyển đổi không gian màu
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# Tạo mặt nạ
min_mau = np.array([ 97, 255, 232])
max_mau = np.array([ 100, 255, 232])
mask = cv2.inRange(hsv_img, min_mau, max_mau)
# sau bước này những đối tượng màu xanh sẽ thành trắng, các màu còn lại là 0
# thực hiện phép and 2 ảnh để lọc
final = cv2.bitwise_and(img, img, mask = mask)
cv2.imshow("Day la buc anh", final)
cv2.waitKey()

-1

# Xử lý video 

Trên môi trường windown, cần cài FFmpeg

```
import cv2
vidcap = cv2.VideoCapture('United.mp4')
success, image = vidcap.read()
count = 0
success = True
while success:
    cv2.imwrite("frame%d.jpg" % count, image)
    success, image = vidcap.read()
    print("Read a new frame:", success)
    count += 1
```

# Tách biên ảnh

In [53]:
img = cv2.imread('./avatar.jpg', 0) # chuyển ảnh xám
# phân ngưỡng
# điểm ảnh từ 100 đến 200 thì thành trắng, ngoài thành đen
img2 = cv2.Canny(img, 100, 200)
cv2.imshow("Thang dzai", img2)
cv2.waitKey()

-1

In [54]:
img2

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0, 255,   0, ...,   0,   0,   0],
       [  0, 255,   0, ...,   0,   0,   0],
       [  0, 255,   0, ...,   0,   0,   0]], dtype=uint8)

# Reading ang loading images with OpenCV and Numpy

In [3]:
import numpy 
import cv2

avatar_image = cv2.imread("./avatar.jpg")
avatar_gray_image = cv2.cvtColor(avatar_image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray avatar", avatar_gray_image)
cv2.imshow("Color avatar", avatar_gray_image)
cv2.imwrite("gray_avatar.jpg", avatar_gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Dòng 1:** Import thư viện numpy, điều này quan tọng bởi vì định dạng ma trận ảnh là kiểu ndarray numpy

**Dòng 2:** Import thư viện OpenCV

**Dòng 4:** Đọc file ảnh avatar.jpg, lưu nó vào biến avatar_image

**Dòng 5:** Chuyển đổi sang ảnh xám sử dụng phương thức cvtColor bởi hằng số COLOR_BGR2GRAY và lưu vào một biến khác gọi là avatar_gray_image

**Dòng 6 và 7:** Hiển thị ảnh

**Dòng 8:** Lưu ảnh với tên file là gray_avatar.jpg

**Dòng 9:** Chờ nhấn 1 phím thì mới tắt hiển thị ảnh

**Dòng 10:** Đóng tất cả các windows

# Loading Videos from a File

# Reading the Video and Writing into a File

# 4. Image Manipulation and Segmentation

### Truy cập và thao tác pixel

In [10]:
import numpy 
import cv2

avatar_image = cv2.imread('./avatar.jpg')
pixel = avatar_image[200,250]

print(pixel)
avatar_image[200, 250] = (255,0,0)

#thay đổi màu thành xanh của một vùng
avatar_image[200:250, 200:350] = (0,255,0)

cv2.imshow('image pixel', avatar_image)
cv2.waitKey(0)

[187 196 193]


-1

### Draw geometric shapes or writing text on a color image

Các hàm: line(), rectangle(), circle(), ellipse(), polygon(), putText()

Chú ý màu ở đây là BGR

```
The functions and syntax are as follows:
• cv2.line(): To draw a line, this function takes the
following arguments:
a. Image object on which the line needs to be drawn
b. Starting point’s pixel coordinates
c. Ending point’s pixel coordinates
d. Color in BGR (not RGB) format
e. Thickness (in pixels)
• cv2.rectangle(): To draw a square or rectangle,
similar to the line() function, this function takes the
following arguments:
a. Image object on which the rectangle needs to be drawn
b. Pixel coordinates of the vertex at the top left
c. Pixel coordinates of the lower-right vertex
d. Color in BGR (not RGB)
e. Thickness (in pixels)
• cv2.circle(): To draw a circle, this function takes the
following arguments:
a. Image object on which the circle needs to be drawn
b. Center pixel’s coordinates
c. Pixel radius of the circle
d. Color in BGR (not RGB)
e. Thickness (in pixels)
• cv2.ellipse(): To draw a ellipse, this function takes
the following arguments:
a. Image object on which the ellipse needs to be drawn
b. Center pixel’s coordinates
c. Length of the minor and major axes
d. Rotation angle of the ellipse (calculated
counterclockwise)
e. Starting angle (calculated clockwise)
f. Final angle (calculated clockwise)
g. Color in BGR (not RGB—be careful)
h. Thickness
• cv2.polyline(): To draw a polygon, this function takes
the following arguments:
a. Image object on which the polygon needs to be drawn
b. The image object on which to draw
c. The array of coordinates
d. True, if it is a closed line
e. Color
f. Thickness
• cv2.putText(): To write text, this function takes the
following arguments:
a. The image on which the text is to be written
b. The text to be written
c. Coordinates of the text’s starting point
d. Font to be used
e. Font size
f. Text color
g. Text thickness
h. The type of line used
```

In [11]:
import numpy as np
import cv2

avatar = cv2.imread('./avatar.jpg')

cv2.line(avatar, (25,21), (100, 100), (255,0,0), 5)
cv2.rectangle(avatar, (25,21), (200, 200), (0, 255,0), 2)
cv2.circle(avatar, (50,50), 50, (0,0,255), -1)

cv2.imshow("Geometry", avatar)
cv2.waitKey(0)

-1

### Filtering Images

In [16]:
import numpy as np
import cv2

avatar = cv2.imread('./avatar.jpg')
# giá trị mỗi điểm ảnh bằng median của các điểm ảnh quanh vùng dc quét
# lọc vùng 3x3
noisereduced_version = cv2.medianBlur(avatar,3)

# lọc vùng 9x9
noisereduced_version2 = cv2.medianBlur(avatar,9)

cv2.imshow("Fillter 1", noisereduced_version)
cv2.imshow("Fillter 2", noisereduced_version2)
cv2.waitKey(0)

-1

![Image](./images/1.png)

### Transfroming Images

In [22]:
import numpy as np
import cv2
# dịch chuyển affine (tuyến tín)
image = cv2.imread('./avatar.jpg')
num_rows, num_cols = image.shape[:2]
# ma trận chuyển đổi, 70 là hướng của x, 110 là hướng của y
translation_matrix = np.float32([[1,0,70], [0,1,110]])
image_translation = cv2.warpAffine(image, translation_matrix, (num_cols, num_rows))
cv2.imshow('Translation', image_translation)
cv2.waitKey()

-1

### Rotation

R = $[[cos(\theta) , -sin(\theta)], [sin(\theta), cos(\theta)]]$

$\theta$ là góc xoay theo hướng ngược chiều kim đồng hồ. OpenCV cung cấp hàm getRotationMatrix2D thay vì lập ma trận này, 
Bạn có thể chỉ định điểm xung quanh mà hình ảnh sẽ được xoay, góc xoay theo độ và hệ số tỷ lệ cho hình ảnh. Khi đã có ma trận chuyển đổi, có thể sử dụng hàm warpAffine().

### image scaling

In [1]:
import cv2
import numpy as np

img = cv2.imread('./avatar.jpg')

img_scaled = cv2.resize(img,None,fx=1.2, fy=1.2, interpolation = cv2.INTER_LINEAR)
cv2.imshow('Scaling - Linear Interpolation', img_scaled)
img_scaled = cv2.resize(img,None,fx=1.2, fy=1.2, interpolation = cv2.INTER_CUBIC)
cv2.imshow('Scaling - Cubic Interpolation', img_scaled)
img_scaled = cv2.resize(img,(450, 400), interpolation = cv2.INTER_AREA)
cv2.imshow('Scaling - Skewed Size', img_scaled)

cv2.waitKey()
cv2.destroyAllWindows()

### Edge Detection

In [ ]:
import cv2
import numpy as np

image = cv2.imread('./avatar.jpg')
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

lower_red = np.array([30, 150, 50])
upper_red = np.array([255, 255, 180])

mask = cv2.inRange(hsv, lower_red, upper_red)
res = cv2.bitwise_and(image, image, mask=mask)

cv2.imshow('origin', image)
edges = cv2.Canny(image, 100, 200)
cv2.imshow('Edges', edges)

cv2.waitKey()
cv2.destroyAllWindows()

### Image segmentation

<font color="red"> LOADING...</font>

## OPENCV TUTORIALS

https://docs.opencv.org/master/d6/d00/tutorial_py_root.html

In [10]:
import cv2 as cv
cv.__version__

'4.1.2'

# 2. Các đặc trưng của Gui trong OpenCV

## 2.1 Getting started with Images

### Mục tiêu:
* Bạn sẽ học về cách đọc một hình ảnh, làm thế nào để hiển thị nó, và làm thế nào để lưu nó.
* Bạn sẽ học về các hàm: `cv.imread()`, `cv.imshow()`, `cv.imwrite()`
* Ngoài ra, bạn sẽ học làm thế nào để hiển thị arh với Matplotlib

### Sử dụng OpenCV
#### Đọc một hình ảnh
Sử dụng hàm `cv.imread()` để đọc một hình ảnh. 

Tham số thứ 2 là cờ chỉ định các đọc:
* `cv.IMREAD_COLOR`: Đọc ảnh màu, đây là tham số mặc định.
* `cv.IMREAD_GRAYSCALE`: Đọc chế độ ảnh xám
* `cv.IMREAD_UNCHANGED`: Tải ảnh bao gồm cả kênh alpha

**Note:** Thay vì sử dụng 3 cờ trên, bạn có thể sử dụng các tương ứng các số nguyên 1, 0 và -1.

**Chú ý:** Ngay cả khi đường dẫn sai, nó sẽ không gây ra lỗi nào, nhưng print img sẽ trả về `None`

In [11]:
import numpy as np
import cv2 as cv

# Load a color image in grayscale
img = cv.imread('./avatar.jpg', 0)

#### Hiển thị một hình ảnh
Sử dụng hàm `cv.imshow()` để hiển thị một hình ảnh lên cửa sổ. Cửa sổ hiển thị sẽ tự động fit cho vừa với kích thước hình ảnh.

Tham số đầu tiên là một string, là tên của cửa sổ hiển thị. Tham số thứ 2 là hình ảnh.Bạn có thể tạo nhiều cửa sổ nếu bạn muốn, nhưng tên các cửa sổ phải khác nhau.

In [13]:
cv.imshow('image', img)
cv.waitKey(0)
cv.destroyAllWindows()

`cv.waitKey()` là một hàm ràng buộc bàn phím. Tham số của nó là thời gian tính bằng mili giây. Hàm sẽ chờ số mini giây được chỉ định cho bất kỳ sự kiện bàn phím nào. Nếu bạn nhấn bất kỳ phím nào trong thời gian đó, chương trình sẽ tiếp tục. Tham số 0 là bỏ qua, nó sẽ chờ vô hạn cho tới khi ấn một phím bất kỳ.

**Note:** Bên cạnh các sự kiện bàn phím ràng buộc, hàm này cũng xử lý nhiều sự kiện GUI khác, vì vậy bạn PHẢI sử dụng nó để thực sự hiển thị hình ảnh.

`cv.destroyAllwindows()`: giải phóng tất cả các cửa sổ tạo ra. Nếu bạn muốn huỷ bất kỳ cửa sổ nào thì có thể dùng hàm `cv.destroyWindow()`, trong đó tham số là tên cửa sổ.

**Note:** Có một trường hợp đặc biệt khi bạn có thể tạo một cửa sổ trống và tải hình ảnh vào nó sau. Trong trường hợp đó, bạn có thể chỉ định xem cửa sổ có thể thay đổi kích thước hay không. Nó được thực hiện với hàm `cv.namedWindow()` . Theo mặc định, cờ là `cv.WINDOW_AUTOSIZE` . Nhưng nếu bạn chỉ định cờ là `cv.WINDOW_NORMAL` , bạn có thể thay đổi kích thước cửa sổ. Sẽ hữu ích khi hình ảnh có kích thước quá lớn và khi thêm thanh theo dõi vào cửa sổ