<b>Câu 1:</b>

a. Tạo 2 tensor 0 chiều ngẫu nhiên x và y với phân phối bất kỳ. <br/>
Tạo một đối tượng Tensorflow trả về x + y nếu x > y và x - y trong trường hợp còn lại. <br/>
Gợi ý: Dùng toàn `tf.cond()`

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

sess = tf.InteractiveSession()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x = tf.random_uniform([])
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y),lambda: x+y,lambda: x-y)
print(sess.run(out))

1.336593


<b><i>Chú ý:</i></b> Mỗi lần chạy sess.run(out) thì đồng thời x và y cũng được khởi tạo lại. Thế nên nếu bạn có in x và y ra rồi in out thì kết quả sẽ không thấy out có dạng x+y và x-y. Bởi vì, khi khởi chạy out thì x và y đồng thời cũng reset và khởi tạo lại.

b. Tạo 2 Tensor 0-d x và y ngẫu nhiên trong khoảng [-1, 1). <br/>
Trả về x+y nếu x<y và x-y nếu x>y và 0 trong trường hợp còn lại <br/>
Gợi ý: Tìm hiểu về `tf.case()` <br/>

In [3]:
x = tf.random.uniform([], minval=-1, maxval=1)
y = tf.random.uniform([], minval=-1, maxval=1)
out = tf.case([(tf.less(x,y),lambda: x+y), (tf.greater(x,y), lambda: x-y)], default=lambda: tf.constant(0.0))
print(sess.run(out))

-0.13406205


c. Tạo tensor x có giá trị là [[0, -2, -1], [0, 1, 2]] <br/>
và y là một tensor zeros với chiều giống như x. <br/>
Trả về một tensor boolean yields True nếu các phần tử x và y bằng nhau tương ứng. <br/>
Gợi ý: Tìm hiểu `tf.equal()`. 

In [4]:
x = tf.constant( [[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)
out = tf.equal(x,y)
print("Tensor x: \n",sess.run(x))
print("Tensor y: \n",sess.run(y))
print("Tensor out: \n", sess.run(out))

Tensor x: 
 [[ 0 -2 -1]
 [ 0  1  2]]
Tensor y: 
 [[0 0 0]
 [0 0 0]]
Tensor out: 
 [[ True False False]
 [ True False False]]


d. Tạo tensor x có giá trị: <br/>
[29.05088806, 27.61298943, 31.19073486, 29.35532951, <br/>
30.97266006, 26.67541885, 38.08450317, 20.74983215, <br/>
34.94445419, 34.45999146, 29.06485367, 36.01657104, <br/>
27.88236427, 20.56035233, 30.20379066, 29.51215172, <br/>
33.71149445, 28.59134293, 36.05556488, 28.66994858] <br/>
Lấy các chỉ số mà phần tử ủa x tại đó lớn hơn 30. <br/>
Gợi ý: Tìm hiểu `tf.where()` <br/>
Rồi extract (xuất) các phần tử có giá trị lớn hơn 30 <br/>
Gợi ý: Tìm hiểu `tf.gather()` <br/>

In [5]:
x = tf.constant([29.05088806, 27.61298943, 31.19073486, 29.35532951,
30.97266006, 26.67541885, 38.08450317, 20.74983215,
34.94445419, 34.45999146, 29.06485367, 36.01657104,
27.88236427, 20.56035233, 30.20379066, 29.51215172,
33.71149445, 28.59134293, 36.05556488, 28.66994858])
out1 = tf.where(tf.greater(x, tf.constant(30.0)))
out2 = tf.gather(x, out1)
print("x:\n", sess.run(x))
print("out1:\n", sess.run(out1))
print("out2:\n", sess.run(out2))

x:
 [29.050888 27.61299  31.190735 29.35533  30.97266  26.675419 38.084503
 20.749832 34.944454 34.45999  29.064854 36.01657  27.882364 20.560352
 30.20379  29.512152 33.711494 28.591343 36.055565 28.669949]
out1:
 [[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
out2:
 [[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


e. Tạo tensor diagnoal 2-d kích cỡ 6x6 với đường chéo (diagonal) có giá trị là 1,2,...,6. <br/>
Gợi ý: Tìm hiểu `tf.range()` và `tf.diag()`

In [6]:
x = tf.diag(tf.range(1,7))
print(sess.run(x))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


f. Tạo tensor 2-d ngẫu nhiên kích cỡ 10x10 từ phân phối bất kỳ. Tính định thức của tensor này. <br/>
Gợi ý: Tìm hiểu `tf.matrix_determinant()`

In [7]:
x = tf.random_uniform((10,10))
deter_x = tf.matrix_determinant(x)
print(sess.run(deter_x))

0.010355058


g. Tạo tensor x với giá trị [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9]. 
Trả về unique các phần tử trong x.  <br/>
Gợi ý: Tìm hiểu `tf.unique()`. Hãy nhớ rằng `tf.unique()` trả về 1 tuple.

In [8]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
unique_x = tf.unique(x)
print("x:\n", sess.run(x))
print("unique of x:\n", sess.run(unique_x))

x:
 [ 5  2  3  5 10  6  2  3  4  2  1  1  0  9]
unique of x:
 Unique(y=array([ 5,  2,  3, 10,  6,  4,  1,  0,  9]), idx=array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8]))


h. Tạo 2 tensor x và y có chiều là 300 từ phân phối bất kỳ, miễn là chúng cùng phân phối. <br/>
Sử dụng `tf.cond()` trả về: <br/>

* MSE (mean squared error) của (x-y) nếu trung bình của tất cả các phần tử trong (x-y) là âm, hoặc <br/>
* Tổng các trị tuyệt đối của tất cả các phần tử trong tensor (x-y) trong các trường hợp còn lại. <br/>
Gợi ý: Xem lại Huber loss function.<br/>

In [9]:
x = tf.random.normal([300])
y = tf.random.normal([300])
def out(x, y):
    sum = tf.reduce_mean(x-y)
    def f1(): return tf.reduce_mean(tf.square(x-y))
    def f2(): return tf.reduce_sum(tf.abs(x-y))
    return tf.cond(sum<0, f1, f2)
print(sess.run(out(x,y)))

346.6408
