Part 1 cung cấp cho bạn các công cụ xử lý NLP. Bạn học về LSA giúp bạn tìm mối liên kết giữa các từ trong topic. Nhưng part 1 mới chỉ xem xét mối quan hệ tuyến tính giữa các từ. Và bạn thường xuyên phải sử dụng yếu tố con người để trích chọn đặc trưng và chọn tham số mô hình. Các mạng neural ở part 2 hoàn thành hầu hết các công việc cho bạn. Và mô hình của part 2 thường chính xác hơn các mô hình mà bạn đã xây dựng ở part 1.

Sử dụng nhiều lớp layer neural network cho machine learning được gọi là <i>deep learning</i>. Trong part 2, chúng ta bắt đầu mở hộp đen deep learning và học cách xây dựng mô hình văn bản phi tuyến tính.

Chương này nói về:
* Lịch sử mạng neural
* Stacking perceptron
* Hiểu lan truyền ngược
* Seeing the knobs to turn on neural networks
* Thực thi một mạng neural cơ bản trong Keras

# 1. Perceptron

Tính toán đầu ra của tế bào thần kinh được mô tả trước đó là đơn giản bằng Python.
Bạn cũng có thể sử dụng NumPy dot chức năng để nhân hai vectơ của bạn với nhau:

In [1]:
import numpy as np

example_input = [1, .2, .1, .05, .2]
example_weights = [.2, .12, .4, .6, .90]

input_vector = np.array(example_input)
weights = np.array(example_weights)
bias_weight = .2

activation_level = np.dot(input_vector, weights) + (bias_weight*1)
activation_level

0.6740000000000002

Các nhân bởi một (* 1) chỉ là để nhấn mạnh
rằng bias_weight cũng giống như tất cả các trọng khác:
nó nhân với một giá trị đầu vào chỉ,
bias_weight giá trị tính năng đầu vào luôn luôn là 1.

Cùng với đó, nếu bạn sử dụng một chức năng kích hoạt ngưỡng đơn giản và chọn một ngưỡng
.5, bước tiếp theo của bạn là những điều sau đây:

In [2]:
threshold = 0.5
if activation_level >= threshold:
    perceptron_output = 1
else:
    perceptron_output = 0
perceptron_output

1

In [5]:
expected_output = 0
new_weights = []
for i, x in enumerate(example_input):
    new_weights.append(weights[i] + (expected_output-perceptron_output)*x)
weights = np.array(new_weights)

In [6]:
example_weights

[0.2, 0.12, 0.4, 0.6, 0.9]

In [7]:
weights

array([-0.8 , -0.08,  0.3 ,  0.55,  0.7 ])

# Keras

In [9]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
# out examples for an exclusive OR (XOR)
x_train = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])
y_train = np.array([[0],
                   [1],
                   [1],
                   [0]])

model = Sequential()
num_neurons = 10
model.add(Dense(num_neurons, input_dim=2))
model.add(Activation('tanh'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                30        
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [12]:
sgd = SGD(lr=0.1)
model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])

In [13]:
model.predict(x_train)

array([[0.5       ],
       [0.4618607 ],
       [0.6156873 ],
       [0.57222056]], dtype=float32)

The predict method gives the raw output of the last layer, which would be generated
by the sigmoid function in this example.

In [17]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 0.6597 - accuracy: 0.5000
Epoch 2/100
4/4 [==============================] - 0s 997us/step - loss: 0.6592 - accuracy: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 1ms/step - loss: 0.6587 - accuracy: 0.5000
Epoch 4/100
4/4 [==============================] - 0s 1ms/step - loss: 0.6582 - accuracy: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 998us/step - loss: 0.6577 - accuracy: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 997us/step - loss: 0.6572 - accuracy: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 1ms/step - loss: 0.6567 - accuracy: 0.5000
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 0.6562 - accuracy: 0.5000
Epoch 9/100
4/4 [==============================] - 0s 1ms/step - loss: 0.6556 - accuracy: 0.7500
Epoch 10/100
4/4 [==============================] - 0s 1ms/step - loss: 0.6551 - accuracy: 0.7500
Epoch 11/100
4/4 [=====

Epoch 84/100
4/4 [==============================] - 0s 1ms/step - loss: 0.5939 - accuracy: 1.0000
Epoch 85/100
4/4 [==============================] - 0s 1ms/step - loss: 0.5927 - accuracy: 1.0000
Epoch 86/100
4/4 [==============================] - 0s 998us/step - loss: 0.5916 - accuracy: 1.0000
Epoch 87/100
4/4 [==============================] - 0s 988us/step - loss: 0.5904 - accuracy: 1.0000
Epoch 88/100
4/4 [==============================] - 0s 996us/step - loss: 0.5891 - accuracy: 1.0000
Epoch 89/100
4/4 [==============================] - 0s 997us/step - loss: 0.5879 - accuracy: 1.0000
Epoch 90/100
4/4 [==============================] - 0s 990us/step - loss: 0.5867 - accuracy: 1.0000
Epoch 91/100
4/4 [==============================] - 0s 1ms/step - loss: 0.5854 - accuracy: 1.0000
Epoch 92/100
4/4 [==============================] - 0s 997us/step - loss: 0.5842 - accuracy: 1.0000
Epoch 93/100
4/4 [==============================] - 0s 1ms/step - loss: 0.5829 - accuracy: 1.0000
Epoch 94

In [18]:
model.predict_classes(x_train)

array([[0],
       [1],
       [1],
       [0]])

In [20]:
model.predict(x_train)

array([[0.38146308],
       [0.54085463],
       [0.5842061 ],
       [0.48153102]], dtype=float32)

## Lưu model đã train

In [21]:
import h5py
# Xuất cấu trúc của mạng đến một JSON blob để sử dụng sau 
# sử dụng phương pháp helper Keras'.
model_structure = model.to_json()
with open("basic_mode.json", "w") as json_file:
    json_file.write(model_structure)
# Các trọng số được đào tạo phải được lưu riêng biệt. Phần đầu tiên
# chỉ tiết kiệm cấu trúc mạng. Bạn phải tái thuyết minh
# cấu trúc cùng một mô hình để tải lại chúng sau này.
model.save_weights("basic_weights.h5")

# MNIST

In [ ]:
def load():
  # download data if not exist
  if not os.path.exists(DATA_FILE):
    download()
  
  # load data
  with gzip.open(DATA_FILE, 'rd') as file:
    tr_dt, v_dt, t_dt = cPickle.load(file)
  
  # training data
  inputs = [x.reshape((784, 1)) for x in tr_dt[0]]
  labels = [label_2_vec(y) for y in tr_dt[1]]
  training_data = zip(inputs, labels)
  
  # validation data
  inputs = [x.reshape((784, 1)) for x in v_dt[0]]
  validation_data = zip(inputs, v_dt[1])
  
  # test data
  inputs = [x.reshape((784, 1)) for x in t_dt[0]]
  test_data = zip(inputs, t_dt[1])
  
  return (training_data, validation_data, test_data)