# CHAPTER I 
## INTRODUCTION TO TENSORFLOW 2.0

- Tensorflow là một thư viện mã nguồn mở dùng để xử lí cách phép tính toán số học bằng cách mô tả một mô hình biểu đồ thể hiện sự thay đổi về giá trị của dữ liệu.
- Thư viện rất phổ biến và có rất nhiều các hàm được xây dựng sẵn cho các bài toán về machine learning, deep learning hay AI. 
- Cài đặt thư viện tensorflow bằng câu lệnh :`pip install tensorflow`. Phiên bản mới nhất của tensorflow là tensorflow `2.3.1`





In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

### 1. So sánh TensorFlow 1 và TensorFlow 2

Tensorflow 1 được ra mắt và được đông đảo cộng đồng CNTT chấp nhận, tuy nhiên phiên bản này vẫn tương đối khó sử dụng. Các nhà nghiên cứu đã ghi nhận những phản hồi và đã tích hợp vào phiên bản `tensorflow 2.0`.
- Chỉnh sửa giúp phiên bản này thân thiện và dễ sử dụng hơn.
- Chỉnh sửa giúp nâng cao hiệu suất.
- Các sửa đổi liên quan đến việc triển khai.

### 2. Tensor + Flow = TensorFlow

Tensor có thể hiểu đơn giản là đại diện cho một số thực (vô hướng), một vector (1 chiều) hay một ma trận (2 chiều). Tổng quát hơn tensor là một mảng nhiều chiều. Tensor có thể thuộc hai loại : `constant` (hằng), ` variable`(biến).
- Rank của một tensor là số chiều của nó.
- Shape là một bộ (tuple) của các số biểu diễn số lượng phần tử có trong mỗi chiều.

Flow có thể hiểu đơn giản là luồng dữ liệu. Nếu phép tensorflow biểu diễn quy trình tính toán bằng một đồ thị, thì các đỉnh của đồ thị là các tensor và dòng chảy tính toán là flow, dòng chảy tính toán này có thể thực hiện các phép tính song song. 


### 3. Các đối tượng trong tensorflow 2

Hằng số (constant) `tf.constant()`

In [3]:
a = tf.constant(10)
b= tf.constant([[0, 1],[2, 3]])
c = tf.constant(9, dtype=tf.float32)
print(a)
print(b)
print(c)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
tf.Tensor(9.0, shape=(), dtype=float32)


Chúng ta có thể hiển thị trực tiếp giá trị của `a`. Khác biệt so với tensorflow 1, khi chúng ta phải tạo session, sau đó run session ấy. 

`a = tf.constant(10)
with tf.Session() as sess:
    print(sess.run(a))` 
    
KL: TensorFlow 2.0 doesn’t require the session execution. (TensorFlow 2 không yêu cầu khởi tạo session).

Biến (variable). `tf.Variable`

Biến là là giá thay đổi trong một đồ thị. Thông thường trong mạng nơ ron thì biến chính là ma trận hệ số của hàm loss function. 

TensorFlow 2.0 doesn’t make it mandatory to initialize variables. (Tensorflow 2 không bắt buộc phải khởi tạo biến)

In [4]:
a = tf.constant(10)
b = tf.constant(15)
c = tf.add(a,b)
d = tf.multiply(a,b)
print(c)
print(d)
x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[5, 6], [7, 8]])
e = tf.Variable(5)
z= tf.matmul(x,y)+e # x*y + e
print(z)

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(150, shape=(), dtype=int32)
tf.Tensor(
[[24 27]
 [48 55]], shape=(2, 2), dtype=int32)


https://github.com/iust-deep-learning/tensorflow-2-tutorial

### 4. Một số các Tensor đặc biệt
Một số câu lệnh khởi tạo các tensor đặc biệt như tensor toàn số 0, tensor toàn 1 hay tensor random

`Tensor 0`

tf.zeros(
    shape, dtype=tf.dtypes.float32, name=None
)

Tạo một tensor 0 bằng một tensor đầu vào

tf.zeros_like(
    input, dtype=None, name=None
)

In [16]:
tf.zeros([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [18]:
t_origin = tf.constant([[[1, 2], 
                         [3, 4]],
                        [[5, 6],
                         [7, 8]]])
t_zeros = tf.zeros_like(t_origin)
print(t_zeros)

tf.Tensor(
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]], shape=(2, 2, 2), dtype=int32)


`tensor one`

In [19]:
t_ones = tf.ones([2, 3, 2],tf.float32)
t_ones_like = tf.ones_like(t_ones)

In [20]:
t_ones

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

`Tensor đơn vị`

tf.eye(num_rows, num_columns=None, batch_shape=None, dtype=tf.dtypes.float32, name=None)

In [21]:
tf.eye(2)
tf.eye(2, num_columns=3)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.]], dtype=float32)>

`Tensor random`

Tensor ngẫu nhiên đầu vào là kích thước, trung bình, độ lệch chuẩn, các phần tử tuân theo phân phối chuẩn.

tf.random.normal(
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)

tf.random.poisson(
    lam, #tham số đặc trưng xác định phân phối poisson
    shape, #kích thước của tensor
    dtype=tf.float32,
    seed=None,
    name=None
)

tf.random.uniform(
    shape, #kích thước của tensor
    minval=0, #giá trị nhỏ nhất
    maxval=None, #giá trị lớn nhất
    dtype=tf.float32,
    seed=None,
    name=None
)

In [24]:
t_random = tf.random.normal([2, 3], mean = 9, stddev = 2)
t_random

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11.412081, 11.60121 ,  8.194072],
       [11.813763, 11.969242, 12.049738]], dtype=float32)>

### 5. Các phép toán trên Tensor

`Element-Wise Operations` (Thực hiện trên từng phần tử ma trận này với ma trận kia)

In [5]:
t1 = tf.constant([[0, 0, 0], [0, 1, 1], [0, 1, 1]])
t2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('t1 + t2 =', t1 + t2)
print('t2 - t1 =', t2 - t1)
print('t1 * t2 =', t1 * t2)
print('t1 / t2 =', t1 / t2)

t1 + t2 = tf.Tensor(
[[ 1  2  3]
 [ 4  6  7]
 [ 7  9 10]], shape=(3, 3), dtype=int32)
t2 - t1 = tf.Tensor(
[[1 2 3]
 [4 4 5]
 [7 7 8]], shape=(3, 3), dtype=int32)
t1 * t2 = tf.Tensor(
[[0 0 0]
 [0 5 6]
 [0 8 9]], shape=(3, 3), dtype=int32)
t1 / t2 = tf.Tensor(
[[0.         0.         0.        ]
 [0.         0.2        0.16666667]
 [0.         0.125      0.11111111]], shape=(3, 3), dtype=float64)


`Matrix Multiplication` (Phép nhân hai ma trận)

In [6]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[10, 20], 
                  [30, 40],
                  [50, 60]])
print("tf.matmul(t1, t2) =", tf.matmul(t1, t2))

tf.matmul(t1, t2) = tf.Tensor(
[[220 280]
 [490 640]], shape=(2, 2), dtype=int32)


`Reshaping` (Định dạng lại kích thước)

In [9]:
t1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9]) # shape :[9]
print(tf.reshape(t, [3, 3]))
t2 = tf.constant([[[1, 1], [2, 2]],
                [[3, 3], [4, 4]]]) # shape :[2, 2, 2]
print(tf.reshape(t2, [2, 4]))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 2 2]
 [3 3 4 4]], shape=(2, 4), dtype=int32)


`Combining Tensors` (Kết hợp các Tensor)

In [11]:
t1 = tf.constant([[1, 1, 1], [1, 1, 1]]) # shape = [2, 3]
t2 = tf.constant([[2, 2, 2], [2, 2, 2]]) # shape = [2, 3]
t3 = tf.constant([[3, 3, 3], [3, 3, 3]]) # shape = [2, 3]
print(tf.concat([t1, t2, t3], axis = 0)) # Kết nối theo hàng
print(tf.concat([t1, t2, t3], axis = 1)) # Kết nối theo cột

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [3 3 3]
 [3 3 3]], shape=(6, 3), dtype=int32)
tf.Tensor(
[[1 1 1 2 2 2 3 3 3]
 [1 1 1 2 2 2 3 3 3]], shape=(2, 9), dtype=int32)


`Reducing` (Tính sum, mean, max, min các phần tử của Tensor)

Để tính mean/max/min của một tensor ta sẽ sử dụng hàm tf.reduce_mean/max/min():


tf.reduce_mean(
    input_tensor,
    axis=None,
    keepdims=None,
    name=None
)

tf.reduce_max(
    input_tensor,
    axis=None,
    keepdims=None,
    name=None
)

tf.reduce_max(
    input_tensor,
    axis=None,
    keepdims=None,
    name=None
)

Kết quả trả về là giá trị theo các chiều

In [15]:
t = tf.constant([[1, 2, 3, 4], 
                 [1, 2, 3, 4]])

# Tính tổng tất cả các phần tử của tensor
print(tf.math.reduce_sum(t))

# Đưa ra tensor chứa tổng các phần tử theo cột
print(tf.math.reduce_sum(t, axis=0))

# Đưa ra tensor chứa tổng các phần tử theo hàng
print(tf.math.reduce_sum(t, axis=1))

t1 = tf.random.uniform(shape=[3, 4], maxval=10, dtype=tf.int32)
print("\nt1 =",t1)

# Phần tử nhỏ nhất của tensor 
print(tf.math.reduce_min(t1))

# Phần tử lớn nhất của tensor 
print(tf.math.reduce_max(t1))

# Phần tử là giá trị trung bình của các phần tử trong tensor
print(tf.math.reduce_mean(t1))

tf.Tensor(20, shape=(), dtype=int32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
tf.Tensor([10 10], shape=(2,), dtype=int32)

t1 = tf.Tensor(
[[6 0 5 6]
 [8 3 2 8]
 [4 0 3 1]], shape=(3, 4), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


Một số các hàm sử dụng phổ biến trong machine learning: `hàm mũ`, `hàm sigmoid`, `hàm relu`, `hàm softmax`, `hàm dấu`, `hàm uniqe`

tf.math.exp(
    x, name=None
)

In [28]:
x = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], dtype = tf.float32)
y = tf.exp(x)
print(y)

tf.Tensor(
[[[2.7182817e+00 7.3890562e+00 2.0085537e+01]
  [5.4598152e+01 1.4841316e+02 4.0342880e+02]
  [1.0966332e+03 2.9809580e+03 8.1030840e+03]]], shape=(1, 3, 3), dtype=float32)


tf.nn.relu(
    features, name=None
)

In [29]:
x = tf.constant([[[1, -2, 3], [4, 5, -6], [7, -8, 9]]], dtype = tf.float32)
y = tf.nn.relu(x)
print(y)

tf.Tensor(
[[[1. 0. 3.]
  [4. 5. 0.]
  [7. 0. 9.]]], shape=(1, 3, 3), dtype=float32)


tf.math.sigmoid(
    x, name=None
)

In [30]:
x = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], dtype = tf.float32)
y = tf.sigmoid(x)
print(y)

tf.Tensor(
[[[0.7310586  0.8807971  0.95257413]
  [0.98201376 0.9933071  0.99752736]
  [0.999089   0.99966455 0.9998766 ]]], shape=(1, 3, 3), dtype=float32)


tf.nn.softmax(
    logits, axis=None, name=None
)

In [31]:
x = tf.constant([1, 1, 2, 3, 4, 5, 6, 7, 8], dtype = tf.float32)
y = tf.nn.softmax(x)
print(y)

tf.Tensor(
[5.7628046e-04 5.7628046e-04 1.5664927e-03 4.2581689e-03 1.1574903e-02
 3.1463847e-02 8.5527599e-02 2.3248814e-01 6.3196826e-01], shape=(9,), dtype=float32)


tf.math.sign(
    x, name=None
)

In [32]:
x = tf.constant([1, 1, -2, 3, 4, 5, -6, -7, 8], dtype = tf.float32)
y = tf.sign(x)
print(y)

tf.Tensor([ 1.  1. -1.  1.  1.  1. -1. -1.  1.], shape=(9,), dtype=float32)


tf.unique(
    x, out_idx=tf.dtypes.int32, name=None
)

Trả ra các giá trị khác nhau và index của nó

In [33]:
x = tf.constant([1, 1, -2, 3, 4, 5, -6, -7, 8], dtype = tf.float32)
y, idx = tf.unique(x)
print(y)
print(idx)

tf.Tensor([ 1. -2.  3.  4.  5. -6. -7.  8.], shape=(8,), dtype=float32)
tf.Tensor([0 0 1 2 3 4 5 6 7], shape=(9,), dtype=int32)


### THAM KHẢO : https://www.tensorflow.org/api_docs/python/tf