# Nội dung kiến thức:
1. One hot encoding
2. Bag of word


# 1. One hot encoding

Chắc hẳn khi làm việc với machine learning và đặc biệt là NLP thì bạn đã nghe thấy nhiều lần cụm từ "one hot encoding" hoặc "one hot vector". Trong NLP, thì one hot endcoding là một trong số nhiều phương pháp mã hoã text sang số, hay còn gọi là word embedding (nhúng từ). 

<b>Word embedding</b> là tên gọi chung của các mô hình ngôn ngữ và các phương pháp học theo đặc trưng trong Xử lý ngôn ngữ tự nhiên(NLP), ở đó các từ hoặc cụm từ được ánh xạ sang các vector số (thường là số thực). Đây là một công cụ đóng vai trò quan trọng đối với hầu hết các thuật toán, kiến trúc Machine Learning, Deep Learning trong việc xử lý Input ở dạng text, do chúng chỉ có thể hiểu được Input ở dạng là số, từ đó mới thực hiện các công việc phân loại, hồi quy,vv…

One hot encoding là phương pháp đơn giản nhất để biểu diễn ngôn ngữ sang dạng vector với số chiều là kích thước bộ từ điển (vocabulary). Các từ được biểu diễn thành một vecto có kích thước bằng từ điển. Vị trí 1 là chỉ số của từ đó trong từ điển, các vị trí khác là 0.

<b>Ví dụ:</b>

Bộ từ điển: V = {Trường, Đại, Học, Bách, Khoa, Hà, Nội} <br/>
Có kích thước S = 7. Biểu diễn theo one-hot thì: <br/>
Trường = [1, 0, 0, 0, 0, 0, 0]<br/>
Đại = [0, 1, 0, 0, 0, 0, 0]<br/>
…<br/>

<b>Thực hành:</b>

Chúng ta cùng thực hành xây dựng one hot vector, giả sử như chúng ta có 1 câu sau:<br/>
<i> Thắng bắt đầu vào đại học Bách Khoa Hà Nội năm 2016, khi đó Thắng 21 tuổi.</i>

In [1]:
sentences = """Thắng bắt đầu vào đại học Bách Khoa Hà Nội năm 2016, khi đó Thắng 21 tuổi."""

Đầu tiên chúng ta cần lấy các token, tức là các từ, ký tự của câu trên, chúng ta cần cắt câu đó ra và tạo bộ từ điển từ câu đó.

In [2]:
token_sequence = sentences.split()
vocabulary =  sorted(set(token_sequence))
vocabulary

['2016,',
 '21',
 'Bách',
 'Hà',
 'Khoa',
 'Nội',
 'Thắng',
 'bắt',
 'học',
 'khi',
 'năm',
 'tuổi.',
 'vào',
 'đó',
 'đại',
 'đầu']

In [3]:
num_token = len(token_sequence)
num_vocabulary = len(vocabulary)
print("Số token:", num_token, "\nSố vocabulary:", num_vocabulary)

Số token: 17 
Số vocabulary: 16


Tạo one hot vector. 

In [4]:
import numpy as np
onehot_vectors = np.zeros((num_token, num_vocabulary), int)
for i, word in enumerate(token_sequence):
    onehot_vectors[i, vocabulary.index(word)] = 1
onehot_vectors

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

Chúng ta thử sử dụng pandas để hiển thị dạng bảng để trực quan hơn. Các cột của pandas tương ứng với bộ từ điển, các hàng tương ứng với từng từ trong câu.

In [5]:
import pandas as pd
pd.DataFrame(onehot_vectors, columns=vocabulary)

2016,  21  Bách  Hà  Khoa  Nội  Thắng  bắt  học  khi  năm  tuổi.  vào  đó  \
0       0   0     0   0     0    0      1    0    0    0    0      0    0   0   
1       0   0     0   0     0    0      0    1    0    0    0      0    0   0   
2       0   0     0   0     0    0      0    0    0    0    0      0    0   0   
3       0   0     0   0     0    0      0    0    0    0    0      0    1   0   
4       0   0     0   0     0    0      0    0    0    0    0      0    0   0   
5       0   0     0   0     0    0      0    0    1    0    0      0    0   0   
6       0   0     1   0     0    0      0    0    0    0    0      0    0   0   
7       0   0     0   0     1    0      0    0    0    0    0      0    0   0   
8       0   0     0   1     0    0      0    0    0    0    0      0    0   0   
9       0   0     0   0     0    1      0    0    0    0    0      0    0   0   
10      0   0     0   0     0    0      0    0    0    0    1      0    0   0   
11      1   0     0   0     0    0      0    0    0    0    0      0    0   0   
12      0   0     0   0     0    0      0    0    0    1    0      0    0   0   
13      0   0     0   0     0    0      0    0    0    0    0      0    0   1   
14      0   0     0   0     0    0      1    0    0    0    0      0    0   0   
15      0   1     0   0     0    0      0    0    0    0    0      0    0   0   
16      0   0     0   0     0    0      0    0    0    0    0      1    0   0   

    đại  đầu  
0     0    0  
1     0    0  
2     0    1  
3     0    0  
4     1    0  
5     0    0  
6     0    0  
7     0    0  
8     0    0  
9     0    0  
10    0    0  
11    0    0  
12    0    0  
13    0    0  
14    0    0  
15    0    0  
16    0    0

Các vector one-hot là rất thưa, chỉ bao gồm một giá trị khác không cho mỗi hàng vector. Vì vậy ta thử thay thế số 0 bằng ký tự rỗng để nhìn trực quan hơn nữa. Tuy nhiên <b>đừng làm như thế này khi xử lý DataFrame cho mô hình máy học của bạn</b>. Vì nó sẽ tạo ra rất nhiều đối tượng rỗng hoặc không phải là số, không xác định ở trong DataFrame của chúng ta.

In [6]:
df = pd.DataFrame(onehot_vectors, columns=vocabulary)
df[df==0] = ''
df

2016, 21 Bách Hà Khoa Nội Thắng bắt học khi năm tuổi. vào đó đại đầu
0                                1                                     
1                                    1                                 
2                                                                     1
3                                                          1           
4                                                                 1    
5                                        1                             
6              1                                                       
7                      1                                               
8                 1                                                    
9                          1                                           
10                                               1                     
11     1                                                               
12                                           1                         
13                                                            1        
14                               1                                     
15        1                                                            
16                                                     1

Ok, hết, phương pháp này khá đơn giản và không có gì, chúng ta rất dễ dàng thiết lập ra các vector one hot cho 1 câu, 1 từ hay 1 đoạn văn giống như cách chúng ta làm bên trên, đây là phương pháp cổ điển nhất và đơn giản nhất trong các phương pháp word embedding, nó có những ưu và nhược điểm riêng.

## Ưu và nhược điểm

### Ưu điểm:

- Đơn giản, dễ cài đặt.

### Nhược điểm:
-	Không biểu diễn được mức độ tương đồng giữa các từ. 
-	Tốn tài nguyên nhưng thông tin lưu trữ lại không được nhiều như số chiều của nó.

# 2. Bag of word

Bắt đầu bằng ví dụ phân loại tin nhắn rác, ta thấy rằng nếu một tin nhắn có chứa cá từ khuyến mại, giảm giá, trúng thưởng, giảm giá cực sốc, Toán Tin không em… nhiều khả năng đó là một tin nhắn rác. Từ đó, phương pháp đầu tiên có thể nghĩ tới là đếm xem trong tin nhắn có bao nhiêu từ thuộc vào các từ nêu trên, nếu số lượng này nhiều hơn một ngưỡng nào đó thì ta quyết định đó là tin rác. (Tất nhiên bài toán thực tế phực tạp hơn nhiều khi các từ có thể được biểu diễn dưới dạng không dấu, hoặc sử dụng teencode, với các văn bản khác nhau, lượng từ liên quan tới từng chủ đề cũng khác nhau.) Từ đó có thể dựa vào ý tưởng này, ta đếm số lượng các từ trong từng thể loại để tạo ra các vectorr đặc trưng cho từng văn bản.

Bag of Words là một thuật toán hỗ trợ xử lý ngôn ngữ tự nhiên và mục đích của BoW là phân loại text hay văn bản. Ý tưởng của BoW là phân tích và phân nhóm dựa theo "Bag of Words"(corpus). Với test data mới, tiến hành tìm ra số lần từng từ của test data xuất hiện trong "bag". Tuy nhiên BoW vẫn tồn tại khuyết điểm, nên TF-IDF là phương pháp khắc phục (sẽ giới thiệu các chương sau). Bạn có thể ứng dụng BoW + TF-IDF vào việc tìm kiếm, phân loại tài liệu, lọc mail spam xác định ý định của người dùng...

Bag-of-words không quan tâm đến thứ tự từ trong câu và  cũng chả quan tâm đến ngữ nghĩa của từ.

Vì BoW không quan tâm đến thứ tự của từ trong câu nên 2 câu <b>Anh yêu em</b> và <b>em yêu Anh</b> khi chuyển sang vector bằng BoW sẽ như nhau.

<b>Ví dụ:</b><br/>
Bộ từ điển: V= {0: Em, 1: tin, 2: toán, 3: đi, 4: ơi}<br/>
Thì câu: “Toán tin đi em ơi em ơi” sẽ được chuyển thành: [2, 1, 1, 1, 2]<br/>
<b>Giải thích:</b><br/>
Đối chiếu với bộ từ điển V, từ vị trí số 0 là từ Em. Trong câu của chúng ta thì có 2 từ em => Tại vị trí số 0 của vector output sẽ là 2.<br/>
Tương tự với từ tin, có 1 từ tin trong câu. => vị trí số 1 của vector output sẽ là 1.<br/>
Và cứ như vậy với các từ còn lại.<br/>

### <b>Thực hành:</b>

Chúng ta sẽ xây dựng BoW dựa trên thư viện có sẵn là sklearn.

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
# Text để training
text = ["toán tin đi em ơi"]
# Tạo đối tượng CointVectorizer để thực hiện transform (chuyển đổi)
vectorizer = CountVectorizer()
# tokenize và xây dựng bộ vocabulary
vectorizer.fit(text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [8]:
# Bộ vacabulary và chỉ số các từ
vectorizer.vocabulary_

{'toán': 2, 'tin': 1, 'đi': 3, 'em': 0, 'ơi': 4}

In [9]:
# Test Bag of word
text_test = ["toán tin đi em ơi em ơi"]
vector = vectorizer.transform(text_test)

In [10]:
print(vector.shape)
print(vector.toarray())

(1, 5)
[[2 1 1 1 2]]


Ngoài cách sử dụng sẵn thư viện, chúng ta hoàn toàn có thể tự xây dựng.

In [11]:
sentence_bow = {}
text = "toán tin đi em ơi"
i=0
for token in sorted(text.split()):
    sentence_bow[token] = i
    i+=1
sentence_bow

{'em': 0, 'tin': 1, 'toán': 2, 'đi': 3, 'ơi': 4}

In [12]:
text_test = "toán tin đi em ơi em ơi"
vector_bow_output = np.zeros(len(sentence_bow))
for token in text_test.split():
    vector_bow_output[sentence_bow[token]] +=1
vector_bow_output

array([2., 1., 1., 1., 2.])

## Ưu và nhược điểm

### Ưu điểm :

- Đơn giản, dễ cài đặt

### Nhược điểm:

- Với những ứng dụng thực tế, vocabulary có thể rất lớn, nhưng vector đặc trưng thu được của văn bản 1 câu hay một tiểu thuyết đều có kích thước bằng nhau.
- Có rất nhiều từ không xuất hiện trong văn bản. Như vậy, các vector đặc trưng thu được thường có rất nhiều phần tử bằng 0 (gọi là sparse vector). Để cải thiện cái đó, ta có thể dùng 1 list các cặp pair lưu những vị trí các từ tồn tại trong văn bản là số lượng xuất hiện của chúng. Tuy nhiên, nếu có hơn 1 nửa số từ trong vocabulary xuất hiện thì cách này lại phản tác dụng.
- Không xử lý được các từ không có trong vocabulary. Hoặc đôi khi có những từ hiếm gặp lại mang thông tin rất quan trọng trong văn bản đó. Phương pháp cải tiến giúp khắc phục nhược điểm này có tên là term frequency-inverse document frequency (TF-IDF) dùng để xác định tầm quan trọng của một từ trong 1 đoạn văn bản dựa trên toàn bộ văn bản trong cơ sở dữ liệu.
-	Nhược điểm lớn nhất của BoW là nó không mang thông tin về thứ tự của các từ, cũng như sự liên kết các câu, các đoạn văn trong văn bản. Ví dụ các câu: “Toán tin không em”, “Em không (vào) toán tin”, “Em toán tin không” khi được trích chọn đặc trưng bằng BoW sẽ cho 3 vector giống hệt nhau, mặc dù ý nghĩa của chúng khác hẳn nhau.